# Generated by Django 5.2.4 on 2025-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsection',
            options={'ordering': ['order'], 'verbose_name': 'Form Section', 'verbose_name_plural': 'Form Sections'},
        ),
        migrations.AddField(
            model_name='formsection',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
