# Generated by Django 5.2.4 on 2025-08-16 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_alter_formsection_options_formsection_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="section",
        ),
        migrations.RemoveField(
            model_name="formsection",
            name="form_field",
        ),
        migrations.AddField(
            model_name="formfield",
            name="form_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="forms.formsection",
            ),
        ),
        migrations.AddField(
            model_name="formsection",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="forms.form",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="options",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
