# Generated by Django 5.2.4 on 2025-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_form_section_remove_formsection_form_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
