# Generated by Django 5.2.4 on 2025-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_id',
            field=models.CharField(default='test', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
