# Generated by Django 5.2.4 on 2025-08-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
