# Generated by Django 5.2.4 on 2025-08-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_form_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='icon',
            field=models.CharField(default='settings', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
