# Generated by Django 5.2.4 on 2025-08-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_form_icon_form_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
