# Generated by Django 5.2.4 on 2025-08-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_formfield_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text_field', 'Text Field'), ('text_area', 'Text Area'), ('email', 'Email'), ('multiselect', 'Multi-select'), ('select', 'Select'), ('select_few', 'Select Few')], max_length=50),
        ),
    ]
