# Generated by Django 5.2.4 on 2025-08-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='is_repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
