# Generated by Django 5.2.4 on 2025-08-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_formsection_is_repeatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='repeatable_count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
