# Generated by Django 5.2.4 on 2025-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_alter_formsubmission_form_alter_formsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.CharField(choices=[('user_generated', 'User Generated'), ('ai_generated', 'AI Generated')], default='user_generated'),
        ),
    ]
