# Generated by Django 5.2.4 on 2025-10-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_form_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text_field', 'Text Field'), ('text_area', 'Text Area'), ('email', 'Email'), ('multiselect', 'Multi-select'), ('select', 'Select'), ('select_few', 'Select Few'), ('image', 'Image')], max_length=50),
        ),
    ]
