# Generated by Django 5.2.4 on 2025-10-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_formsubmission_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='submission_id',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
