# Generated by Django 5.2.4 on 2025-10-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0017_alter_formsubmission_submission_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formsubmission",
            name="submission_id",
        ),
    ]
