# Generated by Django 5.2.4 on 2025-10-07 12:27

import uuid
from django.db import migrations, models


def populate_submission_ids(apps, schema_editor):
    """Populate existing FormSubmission objects with unique submission_ids"""
    FormSubmission = apps.get_model('forms', 'FormSubmission')
    for submission in FormSubmission.objects.all():
        submission.submission_id = str(uuid.uuid4())
        submission.save()


def reverse_populate_submission_ids(apps, schema_editor):
    """Reverse operation - not needed but required for reversibility"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_remove_formsubmission_submission_id"),
    ]

    operations = [
        # Add the field without unique constraint first
        migrations.AddField(
            model_name='formsubmission',
            name='submission_id',
            field=models.CharField(default='temp', editable=False, max_length=100),
            preserve_default=False,
        ),
        # Populate unique values for existing records
        migrations.RunPython(
            populate_submission_ids,
            reverse_populate_submission_ids,
        ),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='formsubmission',
            name='submission_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
