# Generated by Django 5.2.4 on 2025-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20251007_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='submission_id',
        ),
        migrations.AddField(
            model_name='formsection',
            name='form_type',
            field=models.CharField(choices=[('user_generated', 'User Generated'), ('ai_generated', 'AI Generated')], default='user_generated'),
        ),
    ]
