# Generated by Django 5.2.4 on 2025-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_remove_formsubmission_submission_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsection',
            name='form_type',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_type',
            field=models.CharField(choices=[('user_generated', 'User Generated'), ('ai_generated', 'AI Generated')], default='user_generated'),
        ),
    ]
