# Generated by Django 5.2.4 on 2025-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_remove_formsection_form_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsection',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
