# Generated by Django 5.2.4 on 2025-08-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_goal_user_company_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='target_audience',
        ),
    ]
