# Generated by Django 5.2.4 on 2025-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_company_goal_remove_user_company_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_password_set",
            field=models.BooleanField(default=False),
        ),
    ]
