# Generated by Django 5.2.4 on 2025-10-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='type',
            field=models.CharField(choices=[('set_password', 'Set Password'), ('reset_password', 'Reset Password')], default='set_password'),
        ),
    ]
